### ISSUE TITLE
new topic request

### ISSUE THREAD

**Issue by harryhoch** [midas-network/midas-data#1]
Need a   new topic entitled "enviornmental", with subclasses for "land cover" and "climate"

**Comment by LucieContamin** [comment]
Just an idea, to have "land cover - land use" together as one sub-classes and to avoid any confusion and maybe to add "air quality" ?

**Comment by aarcury-quandt** [comment]
I second "Land Cover - Land Use". 

It would be helpful to define climate then decide if there should be subclasses within climate or additional subclasses within environmental.

Additional potential subclasses:
- Natural disasters
- Water quality with possible indicators for rivers/streams/lakes vs municipal vs well.

**Comment by harryhoch** [comment]
I suggest envrionment as one category, with "land--cover/use", "air quality", "natural disasters", and "water quality" as subclasses. @hoganwr, are there any existing ontologies that cover such terms?

**Comment by harryhoch** [comment]
proposed changes https://github.com/midas-network/midas-data/commit/ae868458a5b37fbfbf06d1d1f026a62ba2a2eafb

**Comment by harryhoch** [comment]
land cover /land use are not included yet.
