### ISSUE TITLE
Deprecated term - replaced by

### ISSUE THREAD

**Issue by LucieContamin** [midas-network/midas-data#12]
For the some deprecated terms:, I cannot find the "replace term by" information.
I assumed:
- Software (13) got replaced by Software (IAO10)
- Sequence data (29) by Sequence collection
- Excess mortality (46) by Excess mortality dataset
- Public Health interventions and policies (59) by Control strategy census

Am I correct?

**Comment by harryhoch** [comment]
@hoganwr , please follow-up
