### ISSUE TITLE
Subclass of Population and Molecular

### ISSUE THREAD

**Issue by LucieContamin** [midas-network/midas-data#14]
The entry form for the data catalog does not contain any subclass under "Biological scale - Population" and "Biological scale - Molecular".
The ontology contains multiple subclass for this two terms and they are also present as subclass of "Topic". 

So, I wonder if it's not confusing and ifwe need to keep the subclasses for these 2 terms (Population and Molecular), and if so, can we define how they get classify, please? For example, "data service" is a subclass of "Population", but my understanding is that data service could be available independently of any Biological Scale.

**Comment by hoganwr** [comment]
We should discuss.  We could remove the biological scale terms as parents
of other terms if we all mutually agree.  The original OWL file was created
that way, and I just left in place, unaware completely that it was a
divergence from the entry form.

**Comment by harryhoch** [comment]
@hoganwr. Agree - the scale should be orthogonal to the other topics... Can we keep it that way in the ontology and revise the curation form appropriately?

**Comment by harryhoch** [comment]
remove scale terms as ancestors of others.
