### ISSUE TITLE
Health Systems - subclass

### ISSUE THREAD

**Issue by LucieContamin** [midas-network/midas-data#15]
The term "Health Systems" (50) is deprecated in the ontology and not used in the entry form for the data catalog. However it is a subclass of Health System and might be redundant with the "Health system capacity" and "treatment facility census" terms. 
Should we keep it or should we remove it? If we keep it should it stays as a subclass of Population?

**Comment by hoganwr** [comment]
Indeed health systems has "term replaced by" "treatment facility census".
I think this again speaks to deprecation vs. deletion.  Once we have
clarity on that issue, we can decide how to handle this issue.

**Comment by harryhoch** [comment]
do we need both? The "treatment facility census" sounds ok to me.

**Comment by LucieContamin** [comment]
My first comment was confusing, "Health Systems" (50) is a subclass of Population not Health System. 

"health system capacity" [subclass of "topic"] is defined as "Information about capacity, including hospital beds, PPE supplies, nursing home capacity, testing sites, therapeutics, etc."

And "treatment facility census" is defined as "A census that counts the number of treatment facilities of some kind in a particular geographical region."

So I think it might be interesting to keep both ("health system capacity" and "treatment facility census") with maybe "treatment facility census" [subclass of "health system capacity"] and keep "Health Systems" as deprecated.

**Comment by harryhoch** [comment]
ok. I agree - the number of facilities (treatment facility census) is not the same as their capacity (health system capacity).

**Comment by hoganwr** [comment]
We'lll keep them both and per I think #17 we'll move treatment facility
census underneath healthsystem capacity.  Close #15
