### ISSUE TITLE
Location / Geographical Terms

### ISSUE THREAD

**Issue by LucieContamin** [midas-network/midas-data#16]
The ontology contains 2 terms: "Location specific" and "Geographical" (both subclass of Population). These 2 terms are not used in the entry form for the data catalog. 

Geographical seems to be redundant with the "Geographical Scope" and "Geographical Resolution" we use for the entry. 
Location specific seems to be redundant with "transmission settings" but also "Geographical Resolution"

Should we keep these 2 terms in the ontology?

**Comment by hoganwr** [comment]
Perhaps the resolution is to change the label of "Geographical" to
"Geographical scope", add "Geographical resolution", and deprecate
"Location specific"?  Warrants discussion.

**Comment by harryhoch** [comment]
@hoganwr - this sounds good to me.

**Comment by LucieContamin** [comment]
I am not sure I understand the answer. Just to add some information, "Geographical Scope" and "Geographical Resolution"  are not "topics" but separate fields we use in the metadata entry/data catalog to input geographical information. I am not sure how it fits in the ontology and how they will be define. 
Currently:
- "geographical scope" field is defined as "Name of the location in English at country or ADMIN1 level corresponding  from GEONAMES(if more than 10 different countries possible "Earth" can be used). Also have Continent and Earth information as some data set have data for multiple countries but in the same continent.
- "geographical resolution" field is defined as "Level of details of the location: ADMIN0, ADMIN1, Country, State, … (can be multiple). List comes from GEONAMES class like: " Dependent political entity" or "First-order administrative division", but it also contains common term (from https://en.wikipedia.org/wiki/Administrative_division for example) to help with the data entry"

**Comment by harryhoch** [comment]
@hoganwr will include both. Neither is a topic...

**Comment by LucieContamin** [comment]
I saw that both Geographical term has been added as SubClass of Population, would it be possible to remove the subclass, please?

**Comment by hoganwr** [comment]
So should they be sibling terms at the top level?  They currently are not under topic either.

**Comment by LucieContamin** [comment]
I like the option to have them sibling terms at top level but I am happy to discuss further if necessary
