### ISSUE TITLE
Subclass

### ISSUE THREAD

**Issue by LucieContamin** [midas-network/midas-data#17]
- For the term "Infection case list" , the ontology has it as a subclass of "case counts" but in the data catalog entry form it's only a subclass of "topic". Which one should we choose?

- For the term "Potentially infectious contact data set" (replacement of Transmission settings), the ontology has it as a subclass of "behavior" but in the data catalog entry form it's only a subclass of "topic". Which one should we choose?

- The term "Data service" (replacement of Data retrieval / API), the previous term use to be a subclass of "topic", it is not anymore, could we have it again in topic as in the data catalog entry form) ?

- Could we move "Aid / Responses" as a subclass of "Socio-economic impacts" (as in the data catalog entry form) 

- The ontology contains the term "Treatment facility census" (not in the data catalog entry form yet). Should it be included as a subclass of "Health System Capacity".

**Comment by hoganwr** [comment]
For the first bullet point: (1) depends on how closely ontology must match
form, (2) if very close match is desired then we could either change
ontology or change form.  Happy to go either way

For the second bullet point: ditto.

For the third bullet: yes, we can add Topic as a parent of Data service

For the fourth bullet: Fine, but then what parent should it have?

For the fifth bullet: same idea about matching the data entry form as for
1st and 2nd bullets.  How do things look in the entry form?

**Comment by LucieContamin** [comment]
For the fourth bullet: 
- Could we move "Aid / Responses" as a subclass of "Socio-economic impacts" (as in the data catalog entry form)
 I was thinking of having:
    -  "Topic" as parent of "Socio-economic impacts" 
    -  "Socio-economic impacts"  parent of "Aid / Responses"

**Comment by harryhoch** [comment]
my thoughts...

1. I would put "infection case list" under "case counts"
2. I would go to "behavior"
3.  ok.
4. Agree with @LucieContamin about the 5th bullet.
5. Yes. Subclass "health system capacity".
