### ISSUE TITLE
Potentially infectious contact data set"- Definition

### ISSUE THREAD

**Issue by LucieContamin** [midas-network/midas-data#18]
- For the term "Potentially infectious contact data set" (replacement of Transmission settings), the new definition "a data set that is about one or more potentially infectious contact processes in a population of host organisms" is slightly different than what we has for transmission settings (data about high-risk areas, and places where transmission is likely to happen.). I feel like we are loosing the "high-risk" areas part of the past definition.

**Comment by hoganwr** [comment]
The "high risk" part is captured in the definition of the class
'potentially infectious contact process" in the source ontology (which in
turn is used in the definition of "potentially infectious contact data
set"): "A biological process that brings the organism into sufficiently
close physical proximity to a pathogen population, either in or on a
contaminated thing or an infectious host, such that the organism is likely
but not certain to acquire an infection with the pathogen."

We could bring that class over as well.  We'd need to discuss where to put
it, and the consequence of it not being present on the data entry form,
which again touches on the issue of how exactly the form and ontology must
mirror one another.

**Comment by harryhoch** [comment]
bring the term over. Consider impacts on the form later.
