### ISSUE TITLE
Human daily movement data set - Definition

### ISSUE THREAD

**Issue by LucieContamin** [midas-network/midas-data#19]
For the term "Human daily movement data set" (replacement of Mobility), the new term and definition includes "daily". I am not certain the data will always be at a daily scale

**Comment by hoganwr** [comment]
That is not the sense in which the term is defined.  The term is about what
people do, not the temporal resolution of the data set.  In other words, we
are talking about what the data are about, not the data.

**Comment by LucieContamin** [comment]
It makes more sense, thank you for the clarification.
