### ISSUE TITLE
Clarification of definitions of terms

### ISSUE THREAD

**Issue by harryhoch** [midas-network/midas-data#2]
We need clearer definitions of the types of digital objects, ideally based on prior definitions from existing ontologies

"Dataset": 
-----------
-  Alternative definitions (preference in bold and underlined): 
-  Website containing one or multiple file(s) data in one place, in the same format.
-  A body of structured information describing some topic(s) of interest. (Schema.org)
-  A collection of data, available for access or download in one or more formats
-  A collection of related data records.

For example:
- https://data.humdata.org/dataset/acaps-covid19-government-measures-dataset Limit (all of these examples are entered as “dataset”): 
- Mobility data with the same information with the same column but in different format (currently entered as dataset)
- Online App without model code and user input are limited (to geographic value for example) but with model output in CSV format
- Dashboard with direct download link to file containing data
- COVID Tracker race specific data

Repository
-----------
-  collection of objects within a single infrastructure/organization, with mostly consistent formats and metadata (current definition in the Google Sheet)
- Website containing multiples files in one or multiple folders/webpages, in the same/different format.
- A collection of datasets. (Schema.org)
- Data Catalog		
	 	
For example:
- Italy GitHub repository contains case count, hospital capacity, … in CSV and original data in PDF 
- COVID Tracker website

Data Catalog
-------------
- listing of links out to other objects often on other websites (current definition in the Google Sheet)
- Website containing multiple links to different objects/projects
- A collection of links

For example:
- GISAID
- PubMed COVID19 specific webpage

Software
---------
-  online app or executable files that results in different outputs depending on user-specified inputs (current definition in the Google Sheet)
- the code to executable files (models, …) or online application that the user can interact with (changing some parameters for example) and impact the output.

For example:
- https://gabgoh.github.io/COVID/index.html
- https://github.com/OpenGene/fastv

Dashboard
------------
- graphical "report" interface of various data (current definition in the Google Sheet)
- Website reporting data/model results… without possibility to download the data
- The basic idea of a dashboard is to provide at-a-glance views of some topic, such as the status of a particular group or organization, a consolidated view of distributed data, etc. The amount of detail in a dashboard varies considerably, depending on the purpose of the dashboard.
- Software providing a view of a dataset as a service
- A view of a dataset
- Could be based on one dataset, if the dataset is downloadable than the entry can be entered as “dataset”
- Could be based on multiple datasets, in this case the entry will be entered as “dashboard”

For example:
- Scenario Hub
- ARCGIS dashboard for case/death/hospitalization …
- Tableau dashboard (without link to CSV/TWBX data)

**Comment by hoganwr** [comment]
It's entirely up to the annotators and you which "definitions" (sorry as an ontologist, we mean something entirely different by that word) work best for you.  Again, this is not an ontology.  If you leave the definitions up to me, they're going to end up formal, precise, unambiguous, and as non-circular as I can possibly get them.

**Comment by harryhoch** [comment]
@JohnLevander to look into terms from existing ontologies to reuse
