### ISSUE TITLE
sequence collection - defintion

### ISSUE THREAD

**Issue by LucieContamin** [midas-network/midas-data#20]
For the term "sequence collection" (replacement of Sequence data),  the new definition is "A collection of discontinuous sequences.", I am not sure I understand the definition, would it be possible to have more information?

**Comment by hoganwr** [comment]
The term derives from the sequence ontology, which defines the sequence
collection class using the sequence class.  The sequence ontology defines
'sequence' as "A sequence_feature with an extent greater than zero. A
nucleotide region is composed of bases and a polypeptide region is composed
of amino acids."  Then it defines 'sequence feature' as " Any extent of
continuous biological sequence."

That admittedly is a disastrous set of circularity and contradiction.
Happy to discuss how to fix the problem.  We might abandon the sequence
ontology altogether given the problems here.

**Comment by LucieContamin** [comment]
Thanks for the additional information. The data catalog contains information about sequence data so I think we should keep it. 
The 'sequence' definition sounds good to me ( "A sequence_feature with an extent greater than zero. A
nucleotide region is composed of bases and a polypeptide region is composed
of amino acids."). 
However, I don't understand the "discontinuous" part in the the sequence collection definition. Does that mean only partial sequence? or will it include all "type" of sequence: partial or complete ?

**Comment by harryhoch** [comment]
I assume it means that it could be partial. @hoganwr - does that sound right?

**Comment by hoganwr** [comment]
Yes, it could be partial.  It could be complete.  It could be a set of
non-contiguous stretches of DNA (which by definition would have to be
partial).

**Comment by harryhoch** [comment]
ok. leave as is and accept bad definition from SO
