### ISSUE TITLE
transmission modeling

### ISSUE THREAD

**Issue by LucieContamin** [midas-network/midas-data#23]
For the term "Disease transmission modeling"(replacement of transmission modeling), the new definition: "An algorithm that models the progress of a transmissible disease in a population." is a little different than the previous one: "Estimates of understanding potential impacts of aspects of human behavior on transmission risk , often under different scenarios. ".

**Comment by harryhoch** [comment]
keep first definition as being more general.

**Comment by hoganwr** [comment]
Agree. Closing issue as nothing further to do.

**Comment by hoganwr** [comment]
We could remove the imported class from Apollo-SV and return to the old
one, or we could go with the Apollo-SV definition. Requires discussion.  It
is not clear that you are advocating for one or the other.  For one thing,
there are disease transmission models involving other animals as hosts
(e.g., there used to be one about Foot and Mouth Disease in hooved animals).

**Comment by LucieContamin** [comment]
I agree to go with the Apollo-SV definition ("An algorithm that models the progress of a transmissible disease in a population.") but I am happy to discuss more about it if necessary
