### ISSUE TITLE
Census of vaccination supplies - definition

### ISSUE THREAD

**Issue by LucieContamin** [midas-network/midas-data#24]
For the term "Census of vaccination supplies"(replacement of vaccination), the new definition includes only supplies information whereas, the previous definition included availability, administrations, number of doses, etc. Should we update the new term/definition or should we add more terms around vaccination?

**Comment by hoganwr** [comment]
The new term definitely captures only actual inventory of vaccine doses.

So if we need to also talk about vaccination administration, I'd recommend
adding a new term.  It's likely there's already something in Apollo-SV that
covers it.

Is there another aspect of vaccine supplies/administration/logistics that
we need to capture?

BIll

**Comment by LucieContamin** [comment]
I will check in more details but I think we will need:
- vaccination supplies
- vaccine administration

I also notice we have some vaccine efficacy information sometimes but I don't know if "Control strategy census" is a good place for a new vaccine efficacy topic.
