### ISSUE TITLE
Excess mortality dataset - subclass

### ISSUE THREAD

**Issue by LucieContamin** [midas-network/midas-data#25]
The term "excess mortality dataset" (replacement of excess mortality), is not a subclass of case counts as excess mortality was. Should it be moved to be a subclass of case counts?

**Comment by hoganwr** [comment]
I am not familiar enough with how excess mortality data are represented.
If they are indeed counts, then yes, it would be appropriate to move them.

**Comment by harryhoch** [comment]
@LucieContamin, they are counts, correct?

**Comment by LucieContamin** [comment]
They can be counts (or percents). I don't think we have any rate but it might be possible to have rate also. But the "case counts" can also be expressed in counts, percent of counts, and rates.

**Comment by harryhoch** [comment]
given that percentages are possible, keep under mortality data and not under case counts.
