### ISSUE TITLE
Modeling - Hierarchy

### ISSUE THREAD

**Issue by LucieContamin** [midas-network/midas-data#28]
Could we update the whole "Modeling" hierarchy, to correspond to the data catalog entry form:

Modeling
-  Modeling Purpose (subclass of Modeling)
         -  Parameter Estimation (subclass of Modeling Purpose)
         - Disease transmission model (subclass of Modeling Purpose)
         - Forecasting (subclass of Modeling Purpose)
         - Network Modeling (subclass of Modeling Purpose)
         - Expert opinion forecasts (deprecated) (subclass of Modeling Purpose)
- Modeling Method (subclass of Modeling)
        - Expert assessment / Opinion (#27 ) (subclass of Modeling Method)
        - Compartmental Models (subclass of Modeling Method)
        - Agent-Based models (subclass of Modeling Method)
        -  Statistical models (#27) (subclass of Modeling Method)

**Comment by harryhoch** [comment]
@hoganwr - please review ontology contents and either (a) harmonize with above, or (b) tell us why this approach is not a good idea.
