### ISSUE TITLE
Demographics - new term?

### ISSUE THREAD

**Issue by LucieContamin** [midas-network/midas-data#29]
The ontology contains "Age-stratified" as a subclass of "Population demographic census". This term is not yet in the data catalog entry form but if we add it, should we also add a term for:
- gender
- sex
- race
- ethnicity

**Comment by hoganwr** [comment]
I'm fine either way: deprecating age-stratified or adding the categories
you list.  Depends on your use cases.

**Comment by harryhoch** [comment]
@LucieContamin -  what's your preference?

**Comment by LucieContamin** [comment]
I am also fine either way, but it might be more interesting for the users to have the details of demographic information (age, gender, sex, etc.). 
If we add it, I can easily go back and review the entries with demographics information to add the details.

**Comment by harryhoch** [comment]
@hoganwr - to add these terms under Population demographic census
