### ISSUE TITLE
Need for topics for certain types of medical data

### ISSUE THREAD

**Issue by harryhoch** [midas-network/midas-data#3]
We need new types of medical/observational data:

- Clinical trial data
- Immunogenciity
- Biting rates of mosquitos

possibly others.

**Comment by aarcury-quandt** [comment]
Immunogenicity is usually but not always part of a clinical trial. I could take a gander through the literature, but the immunogenicity studies that I've been a part of were used banked sera, which is reasonably rare.  We could consider subcategories within trials.

- Immunogenicity
- Bridging (in vaccines this is the type of trial used to expand the licensed age group, as in HPV vaccines)
- Efficacy vs effectiveness - this gets dicey and requires knowledge; all the COVID vaccine trials said they were efficacy trials, potentially for licensure reasons, but were pretty much effectiveness trials
- Phases (need to be able to select multiple, as in a Phase 2/3 trial)
- Drug or Device (including diagnostic test)

Other immunity data could include 

- Waning immunity
- Titers
- Fractional dosing studies

Other data

- challenge studies; data could include infectious dose
- viral/parasite load
- elimination/eradication programs - the program I worked on would mostly be longitudinal titers, but others would have different data, including spatial data, and potentially infrastructure information
- any medical data included in surveillance.  Off the top of my head: 
  - symptoms (type and duration)
  - exposure or potential exposure
  - time to onset
  - treatment - Rx (e.g. ceftriaxone) and other (e.g., ECMO)
  - whether they were hospitalized (I think differs from hospitalization, particularly if at individual level)
  - occupation
  - loads and titers as listed above
  - diagnostic testing (in this case it would be PCR vs culture vs serology, which can be meaningfully different for some diseases) 
  - serotype/serovar; the raw data would be molecular, though not necessarily sequence data, and generally unavailable, but the classification is a word (e.g., _Salmonella_ serotype Enteriditis)
- Outbreak 
  - questionnaires (tabulated) - These could be a number of things. Mostly I'm thinking of the ridiculous 80-page things CDC makes for multi-state outbreaks, and you get everything a case might have eaten for the weeks leading up to symptom onset and where it came from
  - reports or summaries - could have contact information or simply be the summary data from questionnaires

**Comment by LucieContamin** [comment]
For the `Biting rates of mosquitos`, I wonder if it makes sense to create a `vector` topic with multiple sub-topic like `vector surveillance`, `biting rates`, ... .  This topic might be also in link with the Issue #4.

**Comment by hoganwr** [comment]
Let me know the specific topics to add and where.  I can make due with descriptions from what's here, plus examples of datasets that fall under these topics.

**Comment by harryhoch** [comment]
@aarcury-quandt, can you clarify specifically, as per @hoganwr's question?

**Comment by aarcury-quandt** [comment]
I think the rate limiting step re: current curation is not having a clinical trial category.  @LucieContamin will have a better immediate understanding of the datasets, but what I saw were repositories/catalogues where we wouldn't select subcategories.  If needed, I can pull together any subcategories we need now working from curated entries.

Lucie may discuss this in the meeting today, but it would be good to have a Medical/Biological -> Clinical Trial or simply a Clinical Trial topic right now and add the rest later.  I'll continue working on the rest of it when I'm done with workshops, but the fact that I'd have to hunt down datasets suggests it is indeed low priority.

**Comment by harryhoch** [comment]
ok. let's discuss today

**Comment by harryhoch** [comment]
see proposed changes in proposed-changes-20210713 branch. https://github.com/midas-network/midas-data/commit/ae868458a5b37fbfbf06d1d1f026a62ba2a2eafb

**Comment by harryhoch** [comment]
Clinical Trial is added. Others to be added as needed.
