### ISSUE TITLE
Laboratory testing facility census - definition

### ISSUE THREAD

**Issue by LucieContamin** [midas-network/midas-data#30]
The term "Laboratory testing facility census" (replacement of testing availability) is define as "A census of facilities that conduct clinical laboratory testing." or the previous term was defined as "Where tests are available, how many tests, etc.". The new definition is restricted to clinical laboratory testing, does that include tests in other places (home-test, in pharmacy, etc.) and if not, should we add it?

**Comment by hoganwr** [comment]
If the intent is to capture the number of tests capable of being performed
regardless of performing site (clinical lab, home, pharmacy, etc.), then
yes, we'll need a new term.

**Comment by LucieContamin** [comment]
I think we might need to have number of tests capable of being performed regardless of performing site  and number of tests done regardless of performing site.

**Comment by hoganwr** [comment]
Decision: we need a new class for number of tests capable of performing / performed (possibly within a given length of time eg month)
