### ISSUE TITLE
Abiotic ecosystem data set - Definition and subclass of

### ISSUE THREAD

**Issue by LucieContamin** [midas-network/midas-data#31]
I understand that the "abiotic ecosystem data set" concerns "data set that is about an abiotic ecosystem or some abiotic ecosystem element."

In this case, should we change:
- climate data set
- air quality
- natural disaster
- Land cover / Land use 
as subclasses of "abiotic ecosystem data set" ? 
I am not certain if Land cover and Land match "abiotic" as it describes biome (for example, desert). Should we use a more generic term for "environmental" information?

Also, would it be possible to add "weather" as a subclass of "abiotic ecosystem data set"?

**Comment by hoganwr** [comment]
In the most recent commit, I thought that is where I put them.  I will
double check.  Yes, we can add weather data.

**Comment by LucieContamin** [comment]
Yes, I apologize I made a mistake, they are already under "abiotic ecosystem data set". Sorry for the confusion.

**Comment by harryhoch** [comment]
@hoganwr to add weather data.

**Comment by LucieContamin** [comment]
I might be incorrect but in the last version of the ontology (version 2022-09-28), it seems that "climate data" is a subclass of "topic" and not "abiotic ecosystem data set". 
Would it be possible to verify, please?

**Comment by hoganwr** [comment]
Correct. We can move climate data set to be a subclass of abiotic ecosystem data set.
