### ISSUE TITLE
Diagnosis/COVID-19

### ISSUE THREAD

**Issue by LucieContamin** [midas-network/midas-data#33]
In the ontology, COVID-19 is a subclass of Diagnosis. In the data catalog entry form, COVID-19 is a subclass of "Disease(s)" (issue #9 )
Should we remove/deprecate Diagnosis and add Disease(s)?

For the Disease(s) subclasses, we currently have:
- Covid-19: https://browser.ihtsdotools.org/?perspective=full&conceptId1=840539006&edition=MAIN/2022-05-31&release=&languages=en
- Monkeypox: https://browser.ihtsdotools.org/?perspective=full&conceptId1=359814004&edition=MAIN/2022-05-31&release=&languages=en
- Human Monkeypox: https://browser.ihtsdotools.org/?perspective=full&conceptId1=359811007&edition=MAIN/2022-05-31&release=&languages=en

For the Pathogen Species subclasses, we currently have:
- SARS_Cov_2: https://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?mode=Info&id=2697049&lvl=3&lin=f&keep=1&srchmode=1&unlock
- Monkeypox Virus: https://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?mode=Info&id=10244&lvl=3&lin=f&keep=1&srchmode=1&unlock

For the Host subclass, we currently have:
- Humans

Should we use the NCBI and SNOMED terms for Disease/Pathogen/Host subclasses??

**Comment by hoganwr** [comment]
When you say "we currently have", what does that mean?  Who is "we"?  And
"where" do you have it?  What is the point of reference?

**Comment by LucieContamin** [comment]
Sorry for the confusion, I mean in the data catalog entry form.

**Comment by hoganwr** [comment]
Thanks!  I see references to that form in other issues you've logged.
Where can I find that form?  We can obviously discuss more in project
meetings.  For now, it would be extremely helpful if there is a "source of
truth" for that form that is accessible online.

**Comment by harryhoch** [comment]
Follow suggestions as per @LucieContamin, using the OBO version of NCBI Taxon.

**Comment by LucieContamin** [comment]
thanks for the update, I just have a small questions. Disease, Pathogen and the different subclass has been added in the Ontology. 
However, "diagnosis" (midas0) is still present and active (without any active subclass), would it be possible to "deprecated" diagnosis as it's not use in the MIDAS catalog and is now redundant with Disease and Pathogen?

**Comment by LucieContamin** [comment]
Also would it be possible to have the terms: Pathogen, Host and Disease without being the subclass of Topic, please?

**Comment by hoganwr** [comment]
So you pathogen, host, and disease as subClassOf owl:Thing only?

And deprecate "Diagnosis"?

**Comment by harryhoch** [comment]
Suggest deprecating diagnosis and making pathogen, host, and disease subclasses of topic. Is that acceptable?

**Comment by LucieContamin** [comment]
For diagnosis, I agree.

For pathogen, host, and disease, currently in the MIDAS DB, they are independent to topic. So, they are not subclasses of anything. I wonder which make is the best: to move them to topic or keep them separate?

**Comment by hoganwr** [comment]
They're already under topic. If that's ok, then we can close this issue.

**Comment by harryhoch** [comment]
ok thanks.
