### ISSUE TITLE
create class for human monkeypox

### ISSUE THREAD

**Issue by hoganwr** [midas-network/midas-data#35]
parent: monkeypox
definition: "A monkeypox disease inhering in a human"

**Comment by LucieContamin** [comment]
When we ask to add Human Monkeypox in the Ontology, the term was active on SNOMED. However, since then the term has been disable and make inactive on SNOMED. 
The parent Monkeypox is still active so I wonder if we should already deprecate "human monkeypox"?

**Comment by hoganwr** [comment]
happy to deprecate it if the consensus is to do so.

**Comment by hoganwr** [comment]
Consensus is to deprecate human monkeypox class
