### ISSUE TITLE
Definitions

### ISSUE THREAD

**Issue by LucieContamin** [midas-network/midas-data#38]
For the term:

- "natural disasters" (midas 23); the definition is: "An  environmental dataset about destruction of human-built sructures and   artifacts by overwhelming natural phenomena such as hurricanes, tornadoes,   tsunamis, earthquakes, and volcano eruptions.". Just to be sure I understand, does it include all kind of environmental issue, like forest fire too? As forests are not human-built structures and artifacts, I am not sure if all kind of natural disaster is included. 

- "census of vaccination supplies" (apollo 609); I am not sure I understand the comment.

**Comment by hoganwr** [comment]
That is an excellent point about "natural disasters". I will update the definition.

What part of the comment on "census of vaccine supplies" is confusing?  It just means that data are typically about vaccine products that share something in common.  That thing in common is usually pathogen (the data are about for examplle covid vaccines and not shingles vaccines).  But sometimes the similarity is some property of the vaccines, like you have to keep them cold.  THat is not my comment, by the way, but a comment that came up in discussion with the Wednesday 4p meeting group.  I put it there for posterity's sake.  So if it is not accurate, then I would also like to have clarification.

**Comment by LucieContamin** [comment]
Thanks for the clarification for the vaccine supplies and I apologize I was not clear. 
The comment starts with a "Motivated my MIDAS coordination center indexing of COVID-19 data, software, etc.   " and an empty line, that's the part that was confusing for me. 
The rest of the comment is helpful and I think its accurate and helpful to keep.

**Comment by hoganwr** [comment]
Thanks, I'll have a look. My recollection is that there are more comments
below the empty line.
