### ISSUE TITLE
Annotation properties

### ISSUE THREAD

**Issue by LucieContamin** [midas-network/midas-data#40]
I just have a question about this section, the term Definition appears 3 times with different id (midas1, midas3, and IAO_0000115). What's the difference between these 3 terms?

**Comment by hoganwr** [comment]
Harry created one when he built the file originally.  The IAO gets imported with all the classes brought in from OBO ontologies.  I am not sure how the midas1 and midas3 versions both got created.  We can move them all to midas1 and deprecate the midas3.  If the duplicate label between midas1 and IAO_0000115 is perceived by others as a big problem, then our only option is really to change the label on midas1.

**Comment by harryhoch** [comment]
I believe these were included before we started importing IAO terms. Can we replace mentions of both midas1 and midas3 with IAO_0000115?

**Comment by harryhoch** [comment]
@hoganwr to fix.

**Comment by hoganwr** [comment]
Fixed by v2022-11-10 release.
