### ISSUE TITLE
Case/death/test/hospitalization term

### ISSUE THREAD

**Issue by LucieContamin** [midas-network/midas-data#41]
Currently on the "2022-09-28" version, we have the terms:

- topic:
    - mortality data (subclass of topic)
        - excess mortality dataset  (subclass of mortality data)
   - control strategy census  (subclass of topic)
        -  laboratory testing capacity (subclass of control strategy census)
        -  laboratory testing facility census (subclass of control strategy census)
   - diagnostic test  (subclass of topic)
   - case counts  (subclass of topic)
        - infection case list (subclass of case counts)
        - hospital stay dataset (subclass of case counts)
        - variant cases (subclass of case counts)
    - health system capacity  (subclass of topic)
        -    treatment facility census (subclass of health system capacity)

We use to have mortality data as a subclass of case counts but following issue #25 and #26 , it has been moved to being a subclass of topic. 

So, I wonder if we should also change the subclass of "hospital" and "test" related terms and maybe regroup them together, if that makes sense?

**Comment by hoganwr** [comment]
I don't understand the recommendation.  Do you want to move 'diagnostic test" under "case counts"?

**Comment by LucieContamin** [comment]
I apologize I was not clear, I will try to rephrase my question.

I noticed that we move all "mortality" terms outside "case counts" in a mortality section.
I also noticed that we have multiple "hospital" terms related in multiple section (case count, health system capacity), and same for "test" related terms that are present in multiple section (case counts, topic, control strategy census). 

So I was wondering if it make sense to regroup all "hospital" related terms together and all "test" related terms together to have something like:
- mortality data (subclass of topic)
        - excess mortality dataset (subclass of mortality data)
- [_Hospital/Health care system related term to be defined_] (subclass of topic)
        - hospital stay dataset (subclass of [_Hospital/Health care system related term to be defined_])
        - health system capacity (subclass of [_Hospital/Health care system related term to be defined_])
        -  treatment facility census (subclass of [_Hospital/Health care system related term to be defined_])
- case counts (subclass of topic)
        -  infection case list (subclass of case counts)
        -  variant cases (subclass of case counts)
-  [_Test related term to be defined_] (subclass of topic)
        - laboratory testing capacity (subclass of [_Test related term to be defined_])
        -  laboratory testing facility census (subclass of [_Test related term to be defined_])
        -  diagnostic test (subclass of [_Test related term to be defined_])
    
I hope it makes more sense now. I am open to discussion as I am not sure if my proposition is a better idea compared to what we currently have.

**Comment by harryhoch** [comment]
@LucieContamin I think there are a couple of issues to consider here. 

Your proposal really hinges on the following:
1. putting "health system capacity" and "treatment facility census" under "hospital", with "hospital stay dataset".
2. creating a new topic with laboratory testing capacity, laboratory testing facility census , and diagnostic test as subclasses.

I think the important thing to note here is that the "treatment facility census" and "health system capacity" are measures of how much the health system can do, as opposed to hospital stays, which measures what happens to patient. They should probably be separate. 

Similarly, lab testing capacity and laboratory testing facility census are measures of what can be done - they can have a subsuming class if desired, but they are different from diagnostic test, which presumably applies to #s of tests performed.

**Comment by LucieContamin** [comment]
Thanks for the clarification, it makes sense. So I guess we should keep it as it is currently.

**Comment by harryhoch** [comment]
@LucieContamin and I have agreed. @hoganwr has yet to implement.

**Comment by LucieContamin** [comment]
Sorry I am getting confused, I thought we were agreeing to keep it as it is currently:
topic:
   - mortality data (subclass of topic)
        - excess mortality dataset (subclass of mortality data)
   - control strategy census (subclass of topic)
        - laboratory testing capacity (subclass of control strategy census)
        - laboratory testing facility census (subclass of control strategy census)
   - diagnostic test (subclass of topic)
   - case counts (subclass of topic)
        - infection case list (subclass of case counts)
         -  hospital stay dataset (subclass of case counts)
        - variant cases (subclass of case counts)
   - health system capacity (subclass of topic)
        - treatment facility census (subclass of health system capacity)

Did I misunderstood?

**Comment by harryhoch** [comment]
ok. that's how it is in the current repository. We're all set.
