### ISSUE TITLE
non-specific terms

### ISSUE THREAD

**Issue by LucieContamin** [midas-network/midas-data#42]
The Data Catalog has a "non-location specific results" checkbox and a "non-disease specific results" checkbox filtering options. 
If I understand correctly, these filters correspond to the entries with an empty field for the geographical and disease information in the MIDAS DB. 
To avoid confusion, we were thinking to add a "non-specific" as option in the disease/pathogen/host dropdown fields in the MIDAS DB. 

For example:
-  if we have an entry about a software like `EpiNow2` (https://catalog.midasnetwork.us/?object_id=124): the entry is treated as "non-specific" for all disease/pathogen/host and geographical information as it's possible to apply it for multiple different disease and location. As a results it has an empty field, or 0 or unspecified in the data catalog for this information and empty fields in the MIDAS DB.  
- However, we can also have the case of a contact rate dataset (https://catalog.midasnetwork.us/?object_id=20): the entry can be link to a location but not associated to any disease/pathogen information as it's not related to any specific disease. 

My questions are: 
- the "non-specific" term seems to apply to both "any" or "no" possibility (for example: all disease, any specific diseases or no disease information in the previous examples). Is that OK or should we differentiate it?
- should we also add a "non-specific" option in the geographical fields in the MIDAS DB?
- should this "non-specific" terms be added in the ontology?
- should we standardize the output in the data-catalog to a "non-specific" term instead of empty field, or 0 or unspecified in these fields?

**Comment by hoganwr** [comment]
I would advocate not putting the non-specific terms in the ontology, as they relate more to epistemology than ontology.

**Comment by harryhoch** [comment]
we shoudn't model non-specific terms explicitly. This is generally not done in ontologies.
