### ISSUE TITLE
transmission settings

### ISSUE THREAD

**Issue by harryhoch** [midas-network/midas-data#5]
"Transmissions settings" are currently listed under "behavior", in the sense of human behavior (gathering in various places) might lead to spread of congtagion.  Examples might include shopping malls, care homes, nightclubs, etc. - see https://figshare.com/articles/dataset/COVID19_settings_of_transmission_-_collected_reports_database/12173343.

However, transmissions settings might include prisons and other domains that might not precisely be associated with behavior. Should this go somewhere else?

**Comment by hoganwr** [comment]
Happy to move it where you like.  This OWL file is not an ontology or ontologically rigorous, just a guide for annotation.  So wherever the folks doing annotation think makes most sense to them is fine.

**Comment by harryhoch** [comment]
Ok.  Suggest we discuss two strategies:

1. Either move this to a higher-level category parallel to behavior.
2.  Rename/redefine behavior to include transmission settings.

@hoganwr, your comment about rigor is well-taken. It would be good to have a discussion of the magnitude of the gaps and what would be needed to make this a rigorous ontology. In any case, we should strive to have definitions/descriptions that are as clear as possible

**Comment by hoganwr** [comment]
Depends on what the use case is.  Originally, I understood this OWL file to be used as a thesaurus like artifact for annotating digital objects.  Thus the organization of it was pragmatically driven to organize things according to how annotators would most easily find terms for annotation.  

We were linking to Apollo-SV classes in another repository to match terms up with formal ontology classes, with rigorous definitions.  I even added classes to Apollo-SV motivated by terms here.

If curation/annotation is no longer the driving force, we could just switch to using the dataset hierarchy in Apollo-SV, which is already rigorous and covers 80-90% of the terms here.

**Comment by harryhoch** [comment]
ok, can we discuss when we meet?

**Comment by harryhoch** [comment]
proposed changes in proposed-changes-20210713 branch...
https://github.com/midas-network/midas-data/commit/ae868458a5b37fbfbf06d1d1f026a62ba2a2eafb
