### ISSUE TITLE
Serology and monoclonal antibody data 

### ISSUE THREAD

**Issue by LucieContamin** [midas-network/midas-data#55]
I am currently adding data about:
- COVID-19 serology, for example: https://data.cdc.gov/Laboratory-Surveillance/2022-Nationwide-Blood-Donor-Seroprevalence-Survey-/ar8q-3jhn/about_data
- RSV monoclonal antibody, for example: https://data.cdc.gov/Pregnancy-Vaccination/Monthly-Nirsevimab-Receipt-and-Intent-Among-Female/8ame-63pc/about_data

Is it correct to note these entries with the topic: "immunogen" (An antigen capable, on its own, of inducing an immune response.) or should I pick (or add) another topic?

Thanks

**Comment by hoganwr** [comment]
We could add:

https://ontobee.org/ontology/CIDO?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FCIDO_0000018
which is "COVID-19 diagnostic process by serological assay".  I couldn't
find anything more general w.r.t. serology that would work.

For monoclonal antibodies,maybe we can create a drug ontology term
'monoclonal antibody therapeutic agent' that defines it along the lines as
a product with monoclonal antibody as part, and that monoclonal antibody
has a clinical drug role (or perhaps we need to be careful to follow FDA
drug vs. biologic distinction, but we could do it)

Fo

**Comment by harryhoch** [comment]
"COVID-19 diagnostic process by serological assay" is a process not a count.
consider adding  new term.

**Comment by harryhoch** [comment]
Is the monoclonal antibody a count? a rate? what is the nature of the data

**Comment by LucieContamin** [comment]
To be precise for the " monoclonal antibody" topic, it's about the estimate number that have, intent or intent not  to receive Nirsevimab (monoclonal antibody treatment) Among Females Aged 18-49 Years Who Have a Baby <8 Months, Are Currently Pregnant, or Are Trying to Get Pregnant (results from a telephone survey)

**Comment by LucieContamin** [comment]
To add more information, the data represent an estimated percentage of persons with the intent or not to receive Nirsevimab from a survey.

**Comment by hoganwr** [comment]
For seroprevalence import the following term into the MIDAS data OWL file: http://purl.obolibrary.org/obo/IDOMAL_0000344

**Comment by harryhoch** [comment]
Suggest measurement of intent to vaccinate as a new term. 

@LucieContamin, isn't Nirsivemab a vaccine? Where do monoclonal antibodies come in?

**Comment by LucieContamin** [comment]
> For seroprevalence import the following term into the MIDAS data OWL file: http://purl.obolibrary.org/obo/IDOMAL_0000344

Thanks for the seroprevalence term, just a quick questions, is it of any importance that the parent of the term seems to be "Malaria specific"? 

> isn't Nirsivemab a vaccine? Where do monoclonal antibodies come in?

That's a good question, I am not sure it is correct to call it a vaccine as the mechanism is slightly different. That's why I was not sure which topic to select. It is reported with Vaccine and it seems that a RSV vaccine exists for the mother but Nirsevimab is different. 

According to CDC: https://www.cdc.gov/vaccines/vpd/rsv/public/child.html
> Nirsevimab contains monoclonal antibodies, which are man-made proteins that protect against RSV. Though it does not activate the immune system the way an infection or vaccine would, a nirsevimab shot provides protection similar to that of a vaccine.

I am not sure the FDA call it vaccine neither: https://www.fda.gov/news-events/press-announcements/fda-approves-new-drug-prevent-rsv-babies-and-toddlers
> [..] U.S. Food and Drug Administration approved Beyfortus (nirsevimab-alip) for the prevention of Respiratory Syncytial Virus (RSV) [...]
> Beyfortus is a monoclonal antibody with activity against RSV. Monoclonal antibodies are laboratory-made proteins that mimic the immune system’s ability to fight off harmful pathogens such as viruses. One dose of Beyfortus, administered as a single intramuscular injection prior to or during RSV season, may provide protection during the RSV season.

**Comment by harryhoch** [comment]
> > For seroprevalence import the following term into the MIDAS data OWL file: http://purl.obolibrary.org/obo/IDOMAL_0000344
> 
> Thanks for the seroprevalence term, just a quick questions, is it of any importance that the parent of the term seems to be "Malaria specific"?
> 

@hoganwr , this is a good question. What do you think? 


> > isn't Nirsivemab a vaccine? Where do monoclonal antibodies come in?
> 
> That's a good question, I am not sure it is correct to call it a vaccine as the mechanism is slightly different. That's why I was not sure which topic to select. It is reported with Vaccine and it seems that a RSV vaccine exists for the mother but Nirsevimab is different.
> 


Good points, @LucieContamin. It looks like Nirvisemab has at least some use as a vaccine. See, for example:

https://www.cdc.gov/vaccines/vpd/rsv/public/child.html

@hoganwr ,  how should we represent this in the ontology?

**Comment by harryhoch** [comment]
1. @hoganwr  to add something in Apollo-SV for seroprevlance
2. Nirvisemab raises several points:
    1. monoclonal antibody is a structural  aspect, vaccine is an application. these are orthogonal
    2. intent to vaccinate - not represented. Might need a new term?
    3. rates of vaccination or raw counts? 
    
    @hoganwr to look into points about Nirvisemab

**Comment by harryhoch** [comment]
estimated rate of vaccination  - differs from rate of vaccination

**Comment by hoganwr** [comment]
Yes there is a big problem with the term being malaria specific, and in a non transparent way.  Another problem is that IDOMAL is an inactive ontology, so we cannot expect to ask someone to change it or add a non-malaria-specific term.  Therefore, I will create the term in Apollo-SV, basing it off the IDOMAL definition.

With respect to nivisemab, I will work on creating terms for "intention to vaccinate" and "nirvisemab immunization" in Apollo-SV, then import those terms back here, and create new releases of both.
