### ISSUE TITLE
Reparenting of certain incident / cumulative case count classes

### ISSUE THREAD

**Issue by hoganwr** [midas-network/midas-data#58]
1. Move incident/cumulative hospitalization count classes underneath hospital stay dataset
2. Move incident/cumulative death count classes underneath mortality data
3. Move incident/cumulative vaccination count classes underneath control strategy census
4. Move vaccination with nirsevimab underneath control strategy census

**Comment by hoganwr** [comment]
5. Move intent to vaccinate and intent to be vaccinated underneath behavior

**Comment by LucieContamin** [comment]
Sorry for missing that the first time, but should we move 3 (incident/cumulative vaccination ) and 4 (vaccination with nirsevimab) under "vaccination administration census (apollo 607)" (subclass of control strategy census) ?

**Comment by LucieContamin** [comment]
Looking into the "case count" class definition in more details, I noticed that it includes "serology", so should we move the new serology class underneath case count too? Thanks

**Comment by hoganwr** [comment]
You had previously suggested grouping serology with immunogen, but I'm
happy to move it under case count.

**Comment by LucieContamin** [comment]
I apologize for the confusion with serology. 

I just re-read the "case counts" definition and as it contains cases, deaths, tests, serology, etc. in the definition, I thought it will make sense to move it all as subclasses of "case counts" to make it easier for the user. 

However, if we implement that change, it's going to have a big impact and I think we already talk about it in the past with a different proposition of hierarchy (see issue #41). 

I  keep going back to the organization of these topics, and not sure what's the best solution:
1. Follow the "case counts" definition
2. Follow the type of data they contains
3. Others?

**Comment by harryhoch** [comment]
@LucieContamin , I don't really understand that the difficulty is in moving things to CaseCounts. Why is this a problem?

another issue for @hoganwr: I'm not sure that "vaccination with nirsevimab" should be its own class. Imagine a use case where we have multiple individuals annotated with different types of vaccinations.  We might want to look specifically at vaccinations with nirsiveminab,  or more broadly at the set of individuals with _any_ type of vaccination. The latter use case would seem to call for a parent class of "vaccination" about "nirsivemab".

**Comment by LucieContamin** [comment]
Thanks for the answer.

About the difficulty on moving the term to case counts, I don't think it will be difficult to implement, it's just that we already talk about it in the past and wanted to found a good solution that does not bring new questions or does not cause the need to re-organize the topic again in the future. I am just trying to find the most "logic" organization, especially as it's used in the data catalog. That's the impact I was talking about.

So currently, we have for topic (**_new term_**):

  - mortality data (subclass of topic)
        - excess mortality dataset (subclass of mortality data)
   - control strategy census (subclass of topic)
        - vaccination administration census (subclass of control strategy census)
        - laboratory testing capacity (subclass of control strategy census)
        - laboratory testing facility census (subclass of control strategy census)
   - diagnostic test (subclass of topic)
   - immunogen (subclass of topic)
   -  _**infectious agent seroprevalence**_ 
   - **_intent to be vaccinated_**
   - **_intent to vaccinate_**
   - **_vaccination with nirsevimab_**
   - case counts (subclass of topic)
        - infection case list (subclass of case counts)
        -  hospital stay dataset (subclass of case counts)
        - variant cases (subclass of case counts)
        - _**cumulative epidemic case count**_ 
        - _**incident epidemic case count**_ 
        - _**cumulative epidemic infection count**_ 
        - _**cumulative epidemic death count**_ 
        - _**incident epidemic death count**_ 
        - _**cumulative epidemic hospitalization count**_ 
        - _**incident epidemic hospitalization count**_ 
        - _**cumulative epidemic vaccination count**_ 
        - _**incident epidemic vaccination count**_
  - behavior (subclass of topic)
        - vaccine hesitancy (subclass of behavior) 

with the `case counts` definition being: 

> Counts of cases, deaths, etc. Often includes multiple types of counts as not compatible with more specific labels. Information about diagnostic tests, results, including serology tests, PCR, and other tests. Can include various methods of estimation, including the COVID-19 Forecast and Scenario Hubs

So I am proposing:

   - control strategy census (subclass of topic)
        - vaccination administration census (subclass of control strategy census)
               -    **_vaccination with nirsevimab_** (subclass of vaccination administration census)
               -   _**cumulative epidemic vaccination count**_ (subclass of vaccination administration census)
               - _**incident epidemic vaccination count**_ (subclass of vaccination administration census)
        - laboratory testing capacity (subclass of control strategy census)
        - laboratory testing facility census (subclass of control strategy census)
   - immunogen (subclass of topic)
   - case counts (subclass of topic)
        -    diagnostic test  (subclass of case counts) (definition: Information about diagnostic tests, results, including serology tests, PCR, and other tests)
                -    _**infectious agent seroprevalence**_   (subclass of diagnostic test)
        -   mortality data (subclass of case counts)
              - excess mortality dataset (subclass of mortality data)
              - _**cumulative epidemic death count**_  (subclass of mortality data)
              - _**incident epidemic death count**_  (subclass of mortality data)
        - infection case list (subclass of case counts)
        -  hospital stay dataset (subclass of case counts)
             - _**cumulative epidemic hospitalization count**_ (subclass hospital stay dataset)
             - _**incident epidemic hospitalization count**_  (subclass hospital stay dataset)
        - variant cases (subclass of case counts)
        - _**cumulative epidemic case count**_ (subclass of case counts)
        - _**incident epidemic case count**_ (subclass of case counts)
        - _**cumulative epidemic infection count**_ (subclass of case counts)
  - behavior (subclass of topic)
        - vaccine hesitancy (subclass of behavior) 
        -    **_intent to be vaccinated_** (subclass of behavior) 
        - **_intent to vaccinate_** (subclass of behavior) 

Does it makes sense? Also my understanding is that we were going to deprecate the new "epidemic" specific term for "broader" term, but I guess the new term should follow the same logic.

And I think this new organization might answer the question about "vaccination with nirsevimab" being subclass of a more broader term, here "vaccination administration census" (definition: a population treatment census that is about one or more vaccinations of organisms in a population)

**Comment by harryhoch** [comment]
Thanks, @LucieContamin, this clarification helps. 

I am generally fine with your proposed changes, with a few comments..

1. Regarding the use of "epidemic" in the counts,  I am concerned about the difference between a named epidemic and seasonal outbreaks. If we have a term labelled "cumulative epidemic case counts",  that would seem wrong for seasonal flue (for example). Can we remove this?

2. If we want to have a topic for "vaccination with nirsevimab", we should be clear what this means. If it is counts of vaccination with nirsivemab", shouldn't it go under cumulative and incident counts"? If it's broader than counts (not sure of the use case here), it shouldn't go under census.
 
Some important questions that we should address: What will the impact of the impact of these changes on existing data be? How can we minimize the disruption caused by these changes?

**Comment by LucieContamin** [comment]
Thanks, to answer your comments:

1. We already have an issue open about that problem, the deprecated the "epidemic" specific terms for a broader definition. (#57, #56)

2. The "vaccination with nirsevimab" definition is "A vaccination against respiratory syncytial virus via the administration of the monoclonal antibody nirsevimab." It does not specify if it's incident/cumulative counts. 
The "vaccination administration census" definition is "a population treatment census that is about one or more vaccinations of organisms in a population".  
My understanding is that vaccination with nirsevimab" is more about what "type" of vaccine is used than number of doses/coverage information. So i guess you are correct and it will make more sense to move it directly under "control strategy census (subclass of topic)"
   - control strategy census (subclass of topic)
        -   **_vaccination with nirsevimab_** (subclass of control strategy census)
        - vaccination administration census (subclass of control strategy census)
               -   _**cumulative epidemic vaccination count**_ (subclass of vaccination administration census)
               - _**incident epidemic vaccination count**_ (subclass of vaccination administration census)


The implementation should not cause any major issue for the existing data, I will verify with Jeff, but I think it's relatively easy to just implement a change of hierarchy, same for the data catalog. But I can verify with John and Jeff.
It might impact the users of the data catalog, in the sense that the topic filter will change) and the new topics are not going to be used a lot at the beginning. 

The only other small issue that I see is that if we want to use all the new terms on the existing data, I will need to do a round of review, which is doable but will take some time.

**Comment by harryhoch** [comment]
Thanks, @LucieContamin.

Yes, we should work on those other issues.

Regarding "vaccination with nirsivemab", can you imagine a dataset that includes that term in a context that is not some sort of count that would therefore belong under "control strategy census"?

I also think that we should have a parent term for vaccine and subterms for specific vaccines.

**Comment by LucieContamin** [comment]
About the "vaccination with nirsivemab": we have coverage (cumulative number and percent, for example [here](https://www.cdc.gov/vaccines/imz-managers/coverage/rsvvaxview/nirsevimab-coverage-children-0-19months.html)). We also have the "intent" of vaccination ([here](https://www.cdc.gov/vaccines/imz-managers/coverage/rsvvaxview/nirsevimab-coverage.html)). The other data that I might collect at some point, if available, are the number of dose available but it's fairly rare that I have a dataset associated to that information. 

To give more context about the current "vaccination" terms we have:
- control strategy census (subclass of topic) 
     -   **_vaccination with nirsevimab (subclass of vaccination administration census)_**
     -  vaccination administration census (subclass of control strategy census)
           - **_cumulative epidemic vaccination count (subclass of vaccination administration census)_** 
           - **_incident epidemic vaccination count (subclass of vaccination administration census)_**
    -  vaccination administration capacity (subclass of control strategy census) (definition: The counts of individuals that could be vaccinated in a population ...)
    - census of vaccination supplies (subclass of control strategy census) (definition: [...] inventory census [...] available vaccine doses of one or more similar vaccines.)
- behavior (subclass of topic)
    - vaccine hesitancy (subclass of behavior)
    - **_intent to be vaccinated (subclass of behavior)_** (An intentionality directed at future participation in a vaccination as the recipient of a vaccine or other immunization.)
    - **_intent to vaccinate (subclass of behavior)_** (An intentionality directed at future participation in a vaccination as the administrator of a vaccine or other immunization to an organism with an immune system.)
 
Another issue has been open to add the intent to have someone else being vaccinated (for example pregnant woman having the intent to have their baby vaccinated) (point 5 of issue #56)

**Comment by harryhoch** [comment]
right. so couldn't the coverage go under cumulative epidemic vaccination count? and intent could be under intent to vaccinate? Agree we need to get the other questions of intent resolved...

**Comment by harryhoch** [comment]
Seems like it can be both vaccination and non-vaccination. Is that the problem?

From: Lucie Contamin ***@***.***>
Date: Monday, March 25, 2024 at 11:53 AM
To: midas-network/midas-data ***@***.***>
Cc: Hochheiser, Harry ***@***.***>, Assign ***@***.***>
Subject: Re: [midas-network/midas-data] Reparenting of certain incident / cumulative case count classes (Issue #58)

The problem we have with "Nirsevimab", at the beginning, is that I was not sure it is a "vaccination" topic. (see Issue #55<https://github.com/midas-network/midas-data/issues/55>). I am still not clear if we agree if it's a vaccination topic or not. I think that's why we need it to be separated from the other "vaccination" topics.

If we say it's a type of "vaccination", then I think we don't need to have the special "Nirsevimab" topic, as it's bring a lot of complexity.
However, if it's not a "vaccination" topic, then I guess that it should be just a subtopic of "control strategy census" and maybe avoid using vaccination in the label

**Comment by LucieContamin** [comment]
Sorry, I am not sure I understand that it can be "both vaccination and non-vaccination.". In my understanding, Nirsevimab is not technically a vaccine but it is reported with vaccine data (as we talked in #58).

**Comment by harryhoch** [comment]
Yes, that's my point. in some cases, it will be considered a vaccine, but in others it will not be. Can we mention it multiple places?
