### ISSUE TITLE
New Cumulative, Incident classes / time frame

### ISSUE THREAD

**Issue by LucieContamin** [midas-network/midas-data#59]
- First question is about the name, they all are singular count ("cumulative epidemic infection count"), does that mean that they represent only one value? For example the cumulative case count of Flu from a specific start date to a specific end date?
The majority of our data are time series so will it cover that type of data?

- Currently, the new "cumulative" classes are all related to epidemic and to a specific time frame. However our data are not always epidemic relative, we don't always start at 0 and/or know the start date, and we don't always have "recent" data (some of our Tycho data are from 1940s). For example we can have:
       - weekly cumulative COVID-19 case counts for a specific region from a specific start date to a specific end date (not always starting at 0, we don't always know the beginning of the count and they sometimes stop reporting in the source format we use, so we don't have the end). 
       - we might also have multiple time series in the same data set, for example weekly cumulative that start over every year in a data set covering multiple years. 
So for the "cumulative" part, can I propose for definition something like this:
`An increasing count of "case/death/vaccine/infection/etc."  in a specific time frame`

**Comment by LucieContamin** [comment]
Thanks for the additional information and the answer.
It seems that moving to more general class (divorcing counts from epidemics) solve that issue.

**Comment by harryhoch** [comment]
so, @LucieContamin, if we just remove "epidemics" from the names will that suffice to resolve the issue? @hoganwr
