### ISSUE TITLE
New topic: visit to ER department

### ISSUE THREAD

**Issue by LucieContamin** [midas-network/midas-data#62]
I forgot to ask to add a topic for "visit to ER department, to match some RSV/FLU data we have, like for example: https://archive.cdc.gov/#/details?url=https://www.cdc.gov/ncird/surveillance/respiratory-illnesses/index.html. 

It's currently tagged under "hospital stay dataset" but it's not matching the definition or did I misunderstood?

Also, if we add a new topic, should it be a subclass of "case count" and be on the same level of "hospital stay dataset (apollo 600)"?

**Comment by hoganwr** [comment]
Currently hospital stay dataset has underneath it as "narrower than" both (1) incident hospitalization count and (2) cumulative hospitalization count. Do you want the same under "ER visit dataset"?

**Comment by LucieContamin** [comment]
That's a very good question, I was not sure what was making more sense with the definition of both term. I was not sure we can count ER visit as a "hospital stay" dataset if that make sense?

**Comment by hoganwr** [comment]
Yes, the question makes sense. The answer is that as currently defined, no, hospitalization data do not cover ER visits.

**Comment by LucieContamin** [comment]
So I guess ER visit should not be under hospital stay (to avoid confusion)

**Comment by LucieContamin** [comment]
I apologize I misunderstood, that's a good question. It's not something we are tracking right now so I don't think that is necessary as of now, but I cannot guarantee we might not need it in the future. However I don't think that's an emergency, so `"ER visit dataset"` should be enough for now. Thank you very much and sorry for the confusion.

**Comment by harryhoch** [comment]
I think it would make sense to do the incident and cumulative...

**Comment by LucieContamin** [comment]
I don't feel strongly about it, if we want to have it already now, it works for me. I will have to update the entries with this information in both case.
