### ISSUE TITLE
Definition update

### ISSUE THREAD

**Issue by LucieContamin** [midas-network/midas-data#9]
As the form has evolved a little bit, should we add the definition for the new open fields in the ontology?
- Disease
- PathogenSpecies
- HostSpecies

**Comment by LucieContamin** [comment]
Just to add some information, these 3 are not "topics" but field we use in the metadata entry/data catalog to input disease, pathogen, and host information. I am not sure it fits in this ontology.

**Comment by harryhoch** [comment]
@hoganwr, where would these fit? It seems that we should be able to say something about these topics?

**Comment by hoganwr** [comment]
Yes we can add them.  Should we also move COVID-19 to be a subclass of
disease?

**Comment by LucieContamin** [comment]
Sorry I am not sure I understand the question, in the last version of the ontology (2022-09-28), these 3 terms are already in the ontology with COVID-19 a subclass of infectious disease subclass of disease. 
I re-open an issue (#33) about them being subclass of topic or not. 
I was proposing to have something like:

- topic
    -  modeling (subclass of topic)
        - .... 
    - ...

- disease 
   - infectious disease (subclass of disease)
       - COVID-19 (subclass of infectious disease)
       - monkeypox (subclass of infectious disease)

- pathogen    
   - Monkeypox virus (subclass of pathogen)
   - Severe acute respiratory syndrome coronavirus 2  (subclass of pathogen)

- host
   - Homo sapiens (subclass of host) 


Topic here is just for example of the level I am talking about, and I happy to discuss this proposition if necessary. Thanks!
